name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

permissions:
  contents: read

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Release
          - Debug

    runs-on: windows-latest

    env:
      SOLUTION_FILE_PATH: SpecifiedRecordsExporter.sln
      ISS_FILE_PATH: SpecifiedRecordsExporter.iss

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION_FILE_PATH }}"

      - name: Build
        run: dotnet publish -f net7.0-windows10.0.19041.0 -p:WindowsPackageType=None -p:SelfContained=true  -c Release

      #- name: Create installer
      #  if: matrix.configuration == 'Release'
      #  run: |
      #    & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "${{ env.ISS_FILE_PATH }}"

      #- name: Upload artifacts
      #  if: matrix.configuration == 'Release'
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Setup
      #    path: Output/*-setup.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            Output/*-setup.exe
